apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api_cetesb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api_cetesb
    spec:
      containers:
      - name: api_cetesb
        image: vixandrade/api_cetesb
        ports:
        - containerPort: 3000
          name: api_cetesb
---
apiVersion: v1
kind: Service
metadata:
  name: api_cetesb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: api_cetesb
